<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QuestoesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Garante que as tabelas necessárias existam
        $this->call(BancasTableSeeder::class);
        $this->call(InstituicoesTableSeeder::class);
        $this->call(DisciplinasTableSeeder::class);
        $this->call(ProvasTableSeeder::class);

        $provaId = DB::table('provas')->first()->id;
        $disciplinas = DB::table('disciplinas')->pluck('id', 'nome');

        $gabarito = [
            1 => 'A',
            2 => 'B',
            3 => 'B',
            4 => 'D',
            5 => 'C',
            6 => 'A',
            7 => 'E',
            8 => 'E',
            9 => 'C',
            10 => 'D',
            11 => 'A',
            12 => 'A',
            13 => 'C',
            14 => 'D',
            15 => 'D',
            16 => 'E',
            17 => 'A',
            18 => 'C',
            19 => 'D',
            20 => 'B',
            21 => 'E',
            22 => 'C',
            23 => 'D',
            24 => 'B',
            25 => 'D',
            26 => 'B',
            27 => 'D',
            28 => 'B',
            29 => 'C',
            30 => 'A',
            31 => 'B',
            32 => 'A',
            33 => 'A',
            34 => 'E',
            35 => 'D',
            36 => 'C',
            37 => 'Anulada',
            38 => 'C',
            39 => 'B',
            40 => 'A',
            41 => 'D',
            42 => 'E',
            43 => 'C',
            44 => 'B',
            45 => 'B',
            46 => 'A',
            47 => 'B',
            48 => 'E',
            49 => 'E',
            50 => 'E',
            51 => 'E',
            52 => 'B',
            53 => 'B',
            54 => 'C',
            55 => 'C',
            56 => 'B',
            57 => 'C',
            58 => 'B',
            59 => 'A',
            60 => 'C',
            61 => 'E',
            62 => 'B',
            63 => 'A',
            64 => 'D',
            65 => 'D',
            66 => 'E',
            67 => 'A',
            68 => 'E',
            69 => 'C',
            70 => 'B',
        ];

        // Definição das questões e alternativas
        $questoesData = [
            // Língua Portuguesa
            1 => ['disciplina_id' => $disciplinas['Língua Portuguesa'], 'enunciado' => 'Um argumento utilizado no texto para explicar o relativo sucesso do ensino remoto durante a pandemia é:', 'alternativas' => ['O baixo custo relacionado ao uso de aplicativos de mensagens.', 'O uso de plataformas de aprendizagem de alta tecnologia.', 'A oportunidade de utilização de imagens e áudios disponíveis na rede.', 'A possibilidade de aprofundamento dos conteúdos de várias disciplinas.', 'A qualidade do acesso às atividades devido à alta conectividade.']],
            2 => ['disciplina_id' => $disciplinas['Língua Portuguesa'], 'enunciado' => 'No parágrafo 5, depois da afirmação de que educadores internacionais estimam que estudantes da educação básica já foram impactados pela falta de escolarização, desenvolve-se a ideia de que', 'alternativas' => ['o ensino remoto mediado por tecnologia permitiu a continuidade da escolarização durante a pandemia.', 'os alunos que foram prejudicados por esse processo precisarão ter aulas ou encontros extras para enfrentar essa ruptura.', 'a alternativa mais produtiva para realizar o ensino remoto tem sido a conexão via aplicativos de mensagens.', 'os professores, em sua grande maioria, mantiveram contato com os alunos por meio dos aplicativos de mensagens.', 'o celular, muitas vezes compartilhado pela família, foi a ferramenta mais utilizada para efetivar as atividades de ensino remoto.']],
            3 => ['disciplina_id' => $disciplinas['Língua Portuguesa'], 'enunciado' => 'No trecho "A importância de cultivar interações entre os estudantes, mesmo que eles não estejam no mesmo ambiente físico" (parágrafo 4), a expressão destacada estabelece com a oração principal a relação de', 'alternativas' => ['condição', 'concessão', 'comparação', 'conformidade', 'proporcionalidade']],
            4 => ['disciplina_id' => $disciplinas['Língua Portuguesa'], 'enunciado' => 'O trecho em que a palavra destacada evidencia a opinião do autor do texto é:', 'alternativas' => ['"o ensino remoto continua a ser a rotina de muitas famílias, atualmente." (parágrafo 1)', '"tem sido se conectar regularmente via aplicativos de mensagens" (parágrafo 2)', '"A maior parte do ensino foi feita pelo celular e, geralmente, por um celular" (parágrafo 3)', '"felizmente, mensagens direcionadas são uma forma relativamente barata de comunicação" (parágrafo 4)', '"Embora seja difícil prever exatamente" (parágrafo 5)']],
            5 => ['disciplina_id' => $disciplinas['Língua Portuguesa'], 'enunciado' => 'A concordância verbal está de acordo com as exigências da norma-padrão da língua portuguesa, na forma verbal destacada em:', 'alternativas' => ['Aspiram-se a bons cargos nas empresas para que seja possível superar os problemas causados pela inflação.', 'Com a chegada da pandemia causada pela Covid-19 fazem dois anos que não viajo nas férias escolares.', 'Nos últimos anos, combatem-se batalhas comerciais cotidianamente, devido às barreiras econômicas.', 'Em várias regiões do nosso país, existe problemas a serem resolvidos em todas as diversas áreas do conhecimento.', 'Para garantir a aprendizagem dos estudantes, precisam-se de equipamentos digitais capazes de atender a demandas escolares.']],
            6 => ['disciplina_id' => $disciplinas['Língua Portuguesa'], 'enunciado' => 'De acordo com a norma-padrão da língua portuguesa, a concordância do termo em destaque está plenamente respeitada em:', 'alternativas' => ['A capacitação dos técnicos e o atendimento aos trabalhadores da área da saúde precisam ser desenvolvidos em todo o país.', 'As famílias dos alunos e os professores da rede pública das diferentes regiões brasileiras devem ser acolhidas pelas direções das escolas.', 'O estudo das diferentes disciplinas e a realização de provas bimestrais, após a chegada da Covid-19, têm sido planejadas com muito cuidado.', 'O tratamento das doenças respiratórias e a vacinação de toda a população devem ser implementadas pelos órgãos responsáveis.', 'Os arquivos escolares e as notas dos estudantes necessitam ser guardadas com o maior sigilo para recuperação no futuro.']],
            7 => ['disciplina_id' => $disciplinas['Língua Portuguesa'], 'enunciado' => 'O pronome oblíquo átono em destaque está colocado de acordo com a norma-padrão em:', 'alternativas' => ['No processo ensino-aprendizagem, o objetivo deve ser desenvolver aptidões para que os alunos sempre mantenham-se em dia com os avanços da ciência.', 'Se reclama muito das dificuldades do ensino remoto devido a problemas de conexão.', 'Os profissionais da educação nunca cansam-se de estudar os conteúdos que possam interessar os alunos nas aulas.', 'Para garantir o progresso dos estudantes, os professores sempre dedicam-se a pesquisar novos métodos de ensino.', 'Quando as escolas se preocuparem em empregar novas metodologias no ensino-aprendizagem, alcançarão melhores resultados.']],
            8 => ['disciplina_id' => $disciplinas['Língua Portuguesa'], 'enunciado' => 'De acordo com a norma-padrão da língua portuguesa, o uso do acento grave indicativo da crase é obrigatório na palavra destacada em:', 'alternativas' => ['A prática de ensino remoto levou as famílias a situações difíceis de comunicação com as instituições de ensino.', 'As aulas remotas surgem como uma alternativa para a redução dos impactos negativos no processo de aprendizagem.', 'As escolas e os professores foram levados a essa prática de ensino remoto, em função da chegada inesperada do vírus.', 'O interesse pelo ensino on-line não tem diminuído porque começou a ser considerado a única opção de escolarização durante a pandemia.', 'Os bons resultados de desempenho dos alunos são obtidos graças a dedicação dos professores no ensino on-line.']],
            9 => ['disciplina_id' => $disciplinas['Língua Portuguesa'], 'enunciado' => 'De acordo com a norma-padrão da língua portuguesa, o emprego adequado da vírgula está plenamente atendido em:', 'alternativas' => ['O ensino remoto, com a pandemia de Covid-19 passou a fazer parte do processo de escolarização em todo o Brasil.', 'A melhor fase do ensino on-line tem sido vivida, atualmente embora permaneça a dúvida se é possível ensinar às crianças de forma remota.', 'Como o país não tinha experiências significativas no ensino remoto, precisou aderir à prática de forma emergencial.', 'A qualidade do ensino remoto era questionada, no passado porém o aprendizado conta com tecnologias que garantem ótimos resultados.', 'Um grande número de pesquisadores tem procurado avaliar, quais são as vantagens e desvantagens da educação a distância.']],
            10 => ['disciplina_id' => $disciplinas['Língua Portuguesa'], 'enunciado' => 'A palavra ou a expressão a que se refere o termo em destaque está corretamente explicitada entre colchetes em:', 'alternativas' => ['"83% dos professores mantinham contato com seus alunos por meio dos aplicativos" (parágrafo 3) - [pesquisadores]', '"Esse uso foi uma grande surpresa, mas é porque não temos outras ferramentas" (parágrafo 3) - [contato]', '"Aprendemos que precisamos dos demais" (parágrafo 4) - [resultados]', '"averiguar os que tiveram ensino mínimo ou nulo e decidir" (parágrafo 5) - [alunos]', '"decidir como enfrentar essa ruptura, com aulas ou encontros extras" (parágrafo 5) - [desenvolvimento]']],
            // Língua Inglesa
            11 => ['disciplina_id' => $disciplinas['Língua Inglesa'], 'enunciado' => 'The main purpose of the text is to', 'alternativas' => ['share ideas on how people can cope with the challenges brought by the pandemic.', 'teach people how to practice social distancing while shopping at local businesses.', 'encourage people to take loans in order to make donations to brick-and-mortar retail stores.', 'let people know that health concerns are not as important as taking care of one\'s finances.', 'suggest that people should engage in diversified activities instead of watching too much TV.']],
            12 => ['disciplina_id' => $disciplinas['Língua Inglesa'], 'enunciado' => 'In the $1^{st}$ paragraph, in the fragment "it\'s no secret the unique challenges of Covid-19 are profoundly shaping our economic climate", the expression it\'s no secret (that) means', 'alternativas' => ['it\'s common knowledge.', 'it\'s never been said before.', 'it\'s partially true.', 'it\'s a bad idea.', 'it\'s an important revelation.']],
            13 => ['disciplina_id' => $disciplinas['Língua Inglesa'], 'enunciado' => 'In the $1^{st}$ paragraph, the word uncertain, in the fragment "in this uncertain time" is formed with the prefix un-. A pair of words formed with prefixes that convey the same meaning is:', 'alternativas' => ['doubtful/joblessness', 'unique / only', 'impossible / discourage', 'certainty / envision', 'inside/intimate']],
            14 => ['disciplina_id' => $disciplinas['Língua Inglesa'], 'enunciado' => 'In the $3^{rd}$ paragraph, in the fragment "These everyday purchases put money back into the economy and prevent it from dipping further into a recession", the pronoun it refers to', 'alternativas' => ['money', 'purchases', 'recession', 'economy', 'back']],
            15 => ['disciplina_id' => $disciplinas['Língua Inglesa'], 'enunciado' => 'In the $4^{th}$ paragraph, in the fragment "In March, the Federal Reserve cut rates drastically to boost economic activity", the verb cut indicates a', 'alternativas' => ['habitual action repeatedly carried out by the Federal Reserve to address certain economic situations.', 'future action to be carried out by the Federal Reserve to address possible problems.', 'promised action to be carried out by the Federal Reserve to address the present economic challenges.', 'one-time action carried out by the Federal Reserve to address the present situation.', 'current action carried out by the Federal Reserve to address a permanent situation.']],
            // Matemática
            16 => ['disciplina_id' => $disciplinas['Matemática'], 'enunciado' => 'Um escriturário mantém um desempenho de preencher 30 relatórios por hora e faz uma pausa de 10 minutos às 13h. Durante a pausa, seu chefe pergunta a que horas receberá todos os relatórios preenchidos. Se falta apenas 1 relatório e meio, e o escriturário pretende manter seu desempenho, a partir de que horas o chefe pode contar com todos os relatórios preenchidos?', 'alternativas' => ['13h02min', '13h03min', '13h10min', '13h12min', '13h13min']],
            17 => ['disciplina_id' => $disciplinas['Matemática'], 'enunciado' => 'Durante um atendimento, o cliente de um banco relata ao gerente de atendimento sua disponibilidade para investir R$400.000,00. O gerente tem ao seu dispor 5 opções de investimento: renda fixa, CDB, fundo de ações, LCI e LCA. Ao cliente foi oferecida uma carteira diversificada de 20%, 10%, 30%, 15% e 25%, respectivamente. Sendo assim, verifica-se que o valor sugerido para', 'alternativas' => ['renda fixa foi de R$80.000,00', 'CDB foi de R$60.000,00', 'fundo de ações foi de R$40.000,00', 'LCI foi de R$100.000,00', 'LCA foi de R$120.000,00']],
            18 => ['disciplina_id' => $disciplinas['Matemática'], 'enunciado' => 'Um fungo está se alastrando na parede, e a área contaminada pelo fungo varia no tempo de acordo com a função A: $[0,\infty)\rightarrow\mathbb{R}$ dada por $A(t)=A_{0}\cdot b^{t},$ em que be R é uma constante maior que 1; $A_{0}$ é a área da parede contamina- da no instante inicial; e $\tilde{A}(t)$ é a área contaminada após t dias. De acordo com esse modelo, depois de quantos dias a área contaminada estará triplicada?', 'alternativas' => ['$\sqrt[b]{3}$', '$\sqrt[3]{b}$', '$log_{b}3$', '$log_{3}b$', '$log_{b}(\frac{1}{3})$']],
            19 => ['disciplina_id' => $disciplinas['Matemática'], 'enunciado' => 'Um casal está muito apaixonado, mas devido à distância de suas casas e ao regime de trabalho dos dois, eles não conseguem se encontrar com a frequência de que gostariam. A moça só tem folga aos sábados, e o rapaz trabalha três dias seguidos, folgando no quarto dia. Se hoje é terça-feira e é dia de folga do rapaz, quantas folgas dele cairão no sábado nos próximos 365 dias?', 'alternativas' => ['4', '8', '12', '13', '15']],
            20 => ['disciplina_id' => $disciplinas['Matemática'], 'enunciado' => 'André, Bianca e Carol precisam pintar um painel de $50m^{2}.$ Para pintar $1m^{2},$ André gasta 12 minutos, Bianca gasta 20 minutos, e Carol, 15 minutos. Supondo-se que os três pintaram, juntos, o mesmo painel, sem fazer pausas e a velocidades constantes, quanto tempo eles levaram para a conclusão da tarefa?', 'alternativas' => ['3h 40min', '4h 10min', '5h 50min', '6h', '6h 20min']],
            // Atualidades do Mercado Financeiro
            21 => ['disciplina_id' => $disciplinas['Atualidades do Mercado Financeiro'], 'enunciado' => 'Fintechs são empresas que', 'alternativas' => ['funcionam com o principal objetivo de compartilhar dados cadastrais entre diferentes instituições financeiras autorizadas pelo Banco Central do Brasil (BCB).', 'prestam serviços ao BCB, notadamente a preparação de Relatórios contendo dados e informações sobre as operações de crédito e de câmbio de todas as instituições financeiras.', 'prestam serviços ao BCB, notadamente a criação de sistemas de informações on-line que permitem o compartilhamento de dados entre diversos órgãos reguladores, como o próprio BCB, a Comissão de Valores Mobiliários (CVM) e a Superintendência de Seguros Privados (Susep).', 'empregam tecnologias digitais de última geração e oferecem serviços financeiros à margem do sistema bancário tradicional, estando, portanto, livres da regulação do BCB.', 'atuam por meio de plataformas on-line, lançando inovações no mercado financeiro, mediante uso intenso de tecnologias digitais com elevado potencial de criação de novos modelos de negócios.']],
            22 => ['disciplina_id' => $disciplinas['Atualidades do Mercado Financeiro'], 'enunciado' => 'Nos últimos anos, o Banco Central do Brasil (BCB), visando a aprimorar a transparência e a segurança na interrelação entre as instituições financeiras e os clientes, tem procurado introduzir novos sistemas de informação por meio de tecnologias digitais. Um desses sistemas, administrados pelo BCB, permite aos cidadãos terem acesso pela internet, de forma rápida e segura, a Relatórios contendo informações sobre seus relacionamentos com as instituições financeiras, suas operações de crédito e operações de câmbio. Trata-se do sistema denominado', 'alternativas' => ['Pix', 'Blockchain', 'Registrato', 'Bitcoin', 'Certificação Digital']],
            23 => ['disciplina_id' => $disciplinas['Atualidades do Mercado Financeiro'], 'enunciado' => 'Um dos objetivos almejados pelo Banco Central do Brasil, ao criar o Pix, é', 'alternativas' => ['reduzir a velocidade de circulação da moeda.', 'inibir a concorrência bancária.', 'aumentar os fluxos de pagamento com cartões eletrônicos.', 'disseminar os fluxos de pagamento de forma eletrônica.', 'aumentar o número de intermediários financeiros envolvidos nos fluxos de pagamentos.']],
            24 => ['disciplina_id' => $disciplinas['Atualidades do Mercado Financeiro'], 'enunciado' => 'O Conselho Monetário Nacional e o...', 'alternativas' => ['...', '...']],
            25 => ['disciplina_id' => $disciplinas['Atualidades do Mercado Financeiro'], 'enunciado' => 'Em 2018, o Banco Central do Brasil autorizou a operação de Sociedade de Crédito Direto (SCD) e Sociedade de Empréstimo entre Pessoas (SEP). Tais instituições são exemplos de', 'alternativas' => ['cooperativas de crédito, que são associações de pessoas, visando a conceder crédito aos seus cooperados em condições mais favoráveis que as praticadas no mercado financeiro.', 'empresas que realizam operações de empréstimo e de financiamento entre pessoas (peer-to-peer lending), utilizando-se de plataformas eletrônicas. Tais empresas são supervisionadas pelo Banco Central do Brasil, mas não são consideradas instituições financeiras.', 'fintechs de crédito que, mediante plataformas eletrônicas, atuam diretamente no mercado financeiro, realizando operações de empréstimo, de financiamento e de aquisição de direitos creditórios.', 'fintechs de crédito que, mediante plataformas eletrônicas, atuam no mercado de capitais, financiando atividades de crédito para pequenas e médias empresas.', 'empresas de crédito que, por atuarem diretamente no mercado eletrônico, não necessitam de autorização prévia do Banco Central do Brasil para funcionar.']],
            // Probabilidade e Estatística
            26 => ['disciplina_id' => $disciplinas['Probabilidade e Estatística'], 'enunciado' => 'Um professor de Matemática, com a intenção de verificar o conhecimento de seus alunos em relação à probabilidade, aplica um exercício. A questão pede para identificar qual das frases representa um evento aleatório. As frases apresentadas foram: I. O sol nascerá amanhã. II. A moeda cair com a face "cara" para cima ao ser lançada. III. A soma dos pontos obtidos no lançamento de dois dados honestos ser 8. IV. Choverá em uma cidade de clima tropical em janeiro. De acordo com as frases, qual(is) representa(m) um evento aleatório?', 'alternativas' => ['I, II e IV', 'II e III', 'I, II, III e IV', 'II, III e IV', 'III e IV']],
            27 => ['disciplina_id' => $disciplinas['Probabilidade e Estatística'], 'enunciado' => 'Em uma campanha de marketing de um banco, a equipe de cientistas de dados resolveu dividir os 10.000 clientes com dívidas em dois grupos: um grupo de teste (2.000 clientes), que recebeu uma promoção para quitar as dívidas, e um grupo de controle (8.000 clientes), que não recebeu a promoção. Ao final da campanha, os cientistas de dados verificaram que 450 clientes do grupo de teste e 1.200 clientes do grupo de controle quitaram suas dívidas. A proporção de clientes do grupo de teste que quitou suas dívidas, e a proporção de clientes que quitou suas dívidas no grupo de controle, são, respectivamente, de', 'alternativas' => ['18,0% e 12,5%', '22,5% e 15,0%', '4,5% e 1,2%', '15,0% e 18,0%', '12,5% e 22,5%']],
            28 => ['disciplina_id' => $disciplinas['Probabilidade e Estatística'], 'enunciado' => 'Uma estudante de Análise de Dados precisa apresentar um trabalho sobre a idade dos clientes de uma agência bancária. Para isso, ela analisou a idade de 15 clientes, resultando nas idades (em anos): 32, 25, 42, 29, 35, 40, 28, 30, 27, 23, 31, 26, 38, 33, 37. Qual a mediana da idade dos clientes, em anos?', 'alternativas' => ['29', '30', '31', '32', '33']],
            29 => ['disciplina_id' => $disciplinas['Probabilidade e Estatística'], 'enunciado' => 'Uma empresa está desenvolvendo uma nova linha de produtos e, para definir os preços, o gerente de marketing pediu ao seu assistente que pesquisasse os preços praticados no mercado. O assistente pesquisou 6 empresas, e os preços encontrados foram: R$ 35,00, R$ 40,00, R$ 45,00, R$ 50,00, R$ 55,00 e R$ 60,00. Qual o desvio padrão dos preços encontrados, em reais?', 'alternativas' => ['R$ 8,16', 'R$ 8,26', 'R$ 8,36', 'R$ 8,46', 'R$ 8,56']],
            30 => ['disciplina_id' => $disciplinas['Probabilidade e Estatística'], 'enunciado' => 'Um banco pretende fazer uma pesquisa com seus clientes para verificar o grau de satisfação com os serviços oferecidos. O gerente da agência decidiu usar uma amostra aleatória de 10% de seus clientes. Considerando que a agência possui 20.000 clientes, qual o tamanho da amostra?', 'alternativas' => ['2.000', '2.100', '2.200', '2.300', '2.400']],
            // Conhecimentos Bancários
            31 => ['disciplina_id' => $disciplinas['Conhecimentos Bancários'], 'enunciado' => 'Sr. Z resolve empreender na área agrícola, estabelecendo sua sede no interior do Brasil onde seus estudos identificaram uma maior necessidade de empregos. Após realizar as contratações de praxe, inicia suas atividades, gerando um forte crescimento na região onde atua. Não desejando aumentar o número de empregados, diante dos custos fixos da mão de obra, resolve ampliar sua produção, negociando com pequenos empreendimentos locais. Necessitando de aporte financeiro, ele apresenta pedido de empréstimo ao Banco Y, que encaminha equipe de auditoria à sede do pretendente. Para surpresa de todos, a auditoria constata em vários pequenos empreendimentos, trabalho infantil não autorizado pela legislação e, por força disso, propõe que o empréstimo seja negado. Nos termos da Política de Responsabilidade Socioambiental do Banco do Brasil, constatado idêntico ilícito por parte de fornecedor, ocorreria a', 'alternativas' => ['manutenção do vínculo contratual, por ser relação exterior.', 'suspensão do vínculo até regularização dos atos.', 'majoração dos juros do empréstimo, pelo risco aumentado.', 'análise da relação temporal com o Banco e o valor dos investimentos.', 'decisão de realizar o empréstimo, para bater as metas gerenciais.']],
            32 => ['disciplina_id' => $disciplinas['Conhecimentos Bancários'], 'enunciado' => 'T é agente fiscal da União Federal, atuando em grupo especial que monitora devedores qualificados. Após divisão interna de trabalho, T fica com a responsabilidade de fiscalizar cinco contribuintes específicos, pois são habituais interessados em procedimentos administrativos, cujo valor é superior a milhões de reais. O trabalho iniciou com o mapeamento das instituições financeiras que mantêm relacionamento negocial com os cinco contribuintes. Ficou apurado que são relevantes os Bancos Z, Y e W, em expressivas movimentações, incluindo depósitos, saques e aplicações financeiras, além de remessas para o exterior. Os dados levantados, no entanto, não são específicos, mas apenas resultado de análise de estatísticas do Banco Central. Para ter acesso ao banco de dados de cada contribuinte, T deve realizar alguns outros atos. Nos Termos da Lei Complementar nº 105/2001, os agentes fiscais tributários da União poderão examinar documentos, livros e registros de instituições financeiras, inclusive os referentes a contas de depósitos e aplicações financeiras,', 'alternativas' => ['havendo processo fiscal em curso.', 'autorizados pelo Banco Central.', 'após diligências locais.', 'mediante convênios com instituições financeiras privadas.', 'livremente']],
            33 => ['disciplina_id' => $disciplinas['Conhecimentos Bancários'], 'enunciado' => 'No Brasil, a fixação da taxa básica de juros da economia (a Selic) está sob a alçada do', 'alternativas' => ['Comitê de Política Monetária', 'Conselho Monetário Nacional', 'Ministério da Economia', 'Banco do Brasil', 'mercado financeiro']],
            34 => ['disciplina_id' => $disciplinas['Conhecimentos Bancários'], 'enunciado' => 'Se o planejamento estratégico do Banco do Brasil fixar, como meta prioritária, a expansão de suas operações no varejo bancário, o público-alvo serão as(os)', 'alternativas' => ['companhias de grande porte', 'governos nas esferas federal, estadual e municipal', 'exportadores', 'importadores', 'clientes individuais']],
            35 => ['disciplina_id' => $disciplinas['Conhecimentos Bancários'], 'enunciado' => 'K pretende realizar atividades financeiras no Brasil, buscando maximizar os lucros de seus inúmeros clientes sediados no exterior. A quase totalidade dos investidores atua nos denominados “paraísos fiscais”. De acordo com as regras da Carta-Circular nº 4001/2020, do Banco Central do Brasil, essas operações devem ser monitoradas na seguinte categoria:', 'alternativas' => ['custos de empresas', 'operações de crédito', 'contratos operacionais', 'atividades internacionais', 'investimentos mercadológicos']],
            // Tecnologia da Informação
            36 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Ao tentar resolver um problema de aprendizado de máquina que separava um evento entre duas classes, um desenvolvedor encontrou uma acurácia de exatamente 90%. Analisando a matriz de confusão, o desenvolvedor constatou que os verdadeiros positivos eram 14169, que os verdadeiros negativos eram 15360, os falsos positivos eram 1501, e os falsos negativos eram', 'alternativas' => ['1778', '1779', '1780', '1781', '1782']],
            37 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Ao construir um protótipo que calculava o risco sanitário de um terreno, um desenvolvedor principiante começou a desenhar um modelo relacional, o que o levou a propor as seguintes tabelas (onde o sublinhado representa a chave primária): Terreno(rua,numero,tipoTerreno,CNPJ,nomeEmpresa,codigoRisco,nomeRisco,probabilidadeRisco) Empresa(CNPJ,nomeEmpresa,CPFs,nomePessoas) Ao revisar o trabalho, um segundo desenvolvedor, mais experiente, detectou as seguintes propriedades: 1. codigoRisco → nomeRisco 2. CNPJ → nomeEmpresa 3. CPF → nomePessoa 4. {rua,numero} → CNPJ 5. Uma empresa possui vários donos, cada um com um CPF único, e um dono pode possuir várias empresas 6. Um terreno pode possuir vários riscos Esse segundo desenvolvedor decidiu, então, colocar as tabelas na terceira forma normal, usando o número mínimo de tabelas. O esquema que possui as seis propriedades detectadas pelo segundo desenvolvedor e que representa todas as informações desejadas pelo primeiro desenvolvedor é', 'alternativas' => ['Terreno(rua,numero,tipoTerreno,CNPJ) Empresa(CNPJ,nomeEmpresa) Dono(CNPJ,CPF) Risco(rua,nome,codigoRisco,probabilidadeRisco) TipoRisco(codigoRisco,nomeRisco) PessoaFisica(CPF,nome)', 'Terreno(rua,numero,tipoTerreno,CNPJ,codigoRisco,probabilidadeRisco) Empresa(CNPJ,nomeEmpresa) Dono(CNPJ,CPF) TipoRisco(codigoRisco,nomeRisco) PessoaFisica(CPF,nome)', 'Terreno(rua,numero,tipoTerreno,CNPJ) Empresa(CNPJ,nomeEmpresa) Risco(rua,nome,codigoRisco,probabilidadeRisco) TipoRisco(codigoRisco,nomeRisco) PessoaFisica(CPF,nome,CNPJ)', 'Terreno(rua,numero,tipoTerreno,CNPJ,nomeEmpresa,codigoRisco,nomeRisco,probabilidadeRisco) Empresa(CNPJ,CPF,nomeEmpresa,nomePessoa)', 'Terreno(rua,numero,tipoTerreno,CNPJ,nomeEmpresa,codigoRisco,probabilidadeRisco) Risco(codigoRisco,nomeRisco) Empresa(CNPJ,CPF,nomeEmpresa,nomePessoa)']],
            38 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Para gerar um gráfico de dispersão, um programador precisava consultar duas tabelas, T1 e T2. Ele decidiu, então, usar um LEFT JOIN, como em SELECT * FROM T1 LEFT JOIN T2 USING (CHAVE); Essa consulta resultou em 214 linhas. Por motivos de segurança, ele fez outra consulta semelhante, apenas trocando o LEFT JOIN por um JOIN, e essa segunda consulta resultou em 190 linhas. O que pode explicar corretamente a quantidade diferente de linhas nas consultas realizadas?', 'alternativas' => ['CHAVE é a chave primária de T1, mas apenas um campo da chave primária de T2.', 'CHAVE é a chave primária de T2, mas apenas um campo da chave primária de T1.', 'T1 possui linhas cujo valor de CHAVE não está presente na T2.', 'T2 possui linhas cujo valor de CHAVE não está presente na T1.', 'T2 possui linhas com todas as chaves presentes em T1, mas com campos nulos.']],
            39 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Ao analisar um conjunto de dados com Python, um programador resolveu usar um dataframe Pandas de nome dp para guardá-los. Em um certo momento, ele resolveu que precisaria usar, apenas, quatro colunas de dados do dataframe: “pais“, “ano“, “renda per capita“ e “expectativa de vida“. Que fragmento de código Python 3 deve ser usado para selecionar, apenas, essas quatro colunas do dataframe dp?', 'alternativas' => ['dp[“pais“,“ano“,“expectativa de vida“,“renda per capita“]', 'dp[[“pais“,“ano“,“expectativa de vida“,“renda per capita“]]', 'dp(“pais“,“ano“,“expectativa de vida“,“renda per capita“)', 'dp([“pais“,“ano“,“expectativa de vida“,“renda per capita“])', 'dp[dp[“pais“,“ano“,“expectativa de vida“,“renda per capita“]]']],
            40 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Ao coletar dados em um sistema compatível com SQL 2008 para fazer uma análise de dados, um programador percebeu que havia dois campos, data_de_nascimento e data_de_emissão_RG, em que o valor de data_de_emissão_RG sempre deve ser mais recente que data_de_nascimento. Percebeu, porém, que em 10% das linhas acontecia o inverso, isto é, data_de_nascimento era mais recente que data_de_emissão_RG. Ele corrigiu os dados nessas linhas, verificando que estavam consistentemente trocados, mas, preocupado que tal problema voltasse a acontecer, resolveu solicitar ao DBA uma alteração da tabela, de forma que data_de_emissão_RG sempre tivesse que ser mais recente que data_de_nascimento. O DBA atendeu adequadamente a esse pedido do programador por meio de uma restrição em SQL 2008 do tipo', 'alternativas' => ['CHECK', 'INSPECT', 'TEST', 'VALIDATE', 'VERIFY']],
            41 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Considere o fragmento de código TypeScript a seguir. const a = <T extends {b: string}>(obj: T) => { <código removido> }; Com relação ao código apresentado acima, a(o)', 'alternativas' => ['função a() retorna um objeto do tipo string.', 'variável a é uma lista de objetos do tipo string.', 'variável a é um dicionário cujas chaves são objetos do tipo string.', 'objeto que for passado para a função a() deve ter um campo b do tipo string.', 'valor retornado pela função a() é um objeto que estende um objeto do tipo string.']],
            42 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Considere o código Python a seguir. import numpy as np a = np.array([[1,2,3],[4,5,6],[7,8,9]]) print (a[a>5]) O que será exibido após esse código ser executado?', 'alternativas' => ['[[False False False] [False False True] [True True True]]', '[[False False False] [False False 6] [7 8 9]]', '[[] [6] [7 8 9]]', '[False False False False False 6 7 8 9]', '[6 7 8 9]']],
            43 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Considere o código Python a seguir. import numpy as np valorAplicado = np.array([5000, 6000, 7000, 8000]) taxaJuros = np.array([1, 2, 3, 4]) resultado = valorAplicado * taxaJuros Ao executar o código acima, o valor final da variável resultado será', 'alternativas' => ['70000', '260000', '[ 5000 12000 21000 32000]', '[[ 5000 10000 15000 20000] [ 6000 12000 18000 24000] [ 7000 14000 21000 28000] [ 8000 16000 24000 32000]]', '[[ 5000 6000 7000 8000] [10000 12000 14000 16000] [15000 18000 21000 24000] [20000 24000 28000 32000]]']],
            44 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Um pesquisador conseguiu uma base de dados que mostrava terrenos classificados de acordo com: • características físicas; • tipo de negócio a ser nele implantado; • risco esperado, que compreendia os rótulos alto, médio, baixo ou nenhum. Decidiu, então, usar um algoritmo de aprendizado de máquina que, a partir das características físicas do terreno e do tipo de negócio a ser nele implantado, aprenderia a determinar o risco esperado, enquadrando o terreno em questão em um daqueles rótulos. Nesse cenário, que algoritmo de aprendizado de máquina é indicado para resolver esse problema?', 'alternativas' => ['PCA', 'K-NN', 'DBSCAN', 'K-Medoids', 'Redes de Kohonen']],
            45 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Após um treinamento em SQL padrão 2008, compatível com ambiente MS SQL Server 2008, um escriturário do Banco Z precisou utilizar os conhecimentos adquiridos para criar uma tabela no sistema de banco de dados desse Banco. A tabela a ser criada é de fornecedores, e tem os seguintes campos: CNPJ, nome do fornecedor e país de origem. As características gerais da tabela são: . o campo CNPJ é chave primária e contém 14 caracteres, sendo que os caracteres devem se ater aos numéricos [“0” a “9”], e o caractere zero “0” não pode ser ignorado, seja qual for a posição dele (início, meio ou fim da chave); . o campo NOME contém 20 caracteres e aceita valor nulo; . o campo PAIS contém 15 caracteres e não aceita valor nulo. Nesse contexto, o comando SQL2008 que cria uma tabela com as características descritas acima é', 'alternativas' => ['CREATE TABLE Fornecedores (CNPJ INTEGER PRIMARY KEY, NOME VARCHAR(20) ACCEPT NULL, PAIS VARCHAR(15) NOT NULL)', 'CREATE TABLE Fornecedores (CNPJ CHAR(14) PRIMARY KEY, NOME VARCHAR(20), PAIS VARCHAR(15) NOT NULL)', 'CREATE TABLE Fornecedores (CNPJ CHAR(14) NOT NULL, NOME VARCHAR(20) NOT NULL, PAIS VARCHAR(15))', 'CREATE TABLE Fornecedores (CNPJ CHAR(14), NOME VARCHAR(20) NOT NULL, PAIS VARCHAR(15) NOT NULL), PRIMARY KEY (CNPJ)', 'CREATE TABLE Fornecedores (CNPJ INTEGER(14) NOT NULL, NOME VARCHAR(20), PAIS VARCHAR(15) NOT NULL), PRIMARY KEY (CNPJ)']],
            46 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Para que fosse mais fácil entender um sistema em desenvolvimento, um desenvolvedor usou um modelo de dados relacional (protótipo) mais simples do que o do banco de dados do sistema corporativo original, sendo que ambos utilizavam o mesmo SGDB PostgreSQL. Cabe ressaltar que esse protótipo utilizava apenas um subconjunto dos dados do sistema corporativo original e realizava apenas consultas. Uma forma de garantir que os dados desse protótipo estejam sempre completamente atualizados em relação aos dados reais, com baixo impacto tanto na operação quanto no desempenho do sistema corporativo original, é', 'alternativas' => ['criar apenas VIEWS no protótipo, definidas com consultas sobre as tabelas do sistema corporativo original.', 'implantar TRIGGERS a cada INSERT, em todas as tabelas do sistema corporativo original, atualizando as tabelas do protótipo.', 'implantar TRIGGERS de atualização a cada SELECT, em todas as tabelas do protótipo.', 'particionar as tabelas da base do sistema corporativo original escolhendo um RANGE adequado ao trabalho do protótipo.', 'utilizar DUMP da base do sistema corporativo original e PSQL para a base do protótipo, a cada seção de trabalho, para atualizar a base do protótipo.']],
            47 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Considere o código HTML a seguir. <!doctype html> <html lang=”pt-br”> <head> <script src=”script.js”></script> </head> <body> <form> Texto: <input type=’text’ name=’texto’ id=’idTexto’ class=’classe-input’ value=’Texto inicial’><br> <input type=’submit’ value=’Envia’> </form> </body> </html> Considere, também, o arquivo TypeScript script.ts, listado a seguir, que irá gerar o arquivo script.js no mesmo diretório do arquivo HTML, apresentado acima. onload = (event) => { const texto = document.querySelector(’???’) as HTMLInputElement; console.log(’Texto inicial: ’, texto.value); }; Que texto o programador deverá utilizar no lugar de ???, no código do arquivo TypeScript script.ts, para exibir o valor do campo HTML input na console?', 'alternativas' => ['#classe-input', '#idTexto', '#texto']],
            48 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Um programador precisa criar uma função JavaScript de alto nível para aplicar um filtro a um array de números inteiros, eliminando todos os números que sejam divisíveis por 3. A função deve retornar o novo array sem os números filtrados. Das alternativas a seguir, qual código Python 3 implementa essa função de forma correta e eficiente?', 'alternativas' => ['def filter_divisible_by_three(numbers): return [number for number in numbers if number % 3 != 0]', 'def filter_divisible_by_three(numbers): filtered_numbers = [] for number in numbers: if number % 3 != 0: filtered_numbers.append(number) return filtered_numbers', 'def filter_divisible_by_three(numbers): return list(filter(lambda x: x % 3 != 0, numbers))', 'def filter_divisible_by_three(numbers): return [number for number in numbers if number % 3 == 0]', 'def filter_divisible_by_three(numbers): return list(map(lambda x: x % 3 != 0, numbers))']],
            49 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'No contexto da Engenharia de Software, o termo que se refere a um conjunto de práticas e técnicas que visam a melhorar a qualidade do código, a eficiência do desenvolvimento e a colaboração entre os membros da equipe é', 'alternativas' => ['Design Patterns', 'Test-Driven Development (TDD)', 'Behavior-Driven Development (BDD)', 'Domain-Driven Design (DDD)', 'Clean Code']],
            50 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Considere o seguinte fragmento de código Python. def calculate(a, b): return a + b print(calculate(1, 2)) O que será exibido após esse código ser executado?', 'alternativas' => ['1', '2', '3', 'Error', 'SyntaxError']],
            51 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'A empresa em que um cientista de dados trabalha precisa fazer uma análise de dados sobre a idade de seus clientes. Para isso, o cientista de dados precisa encontrar a idade média e a idade que mais se repete (moda). Qual das alternativas a seguir é a melhor forma de calcular esses valores em Python?', 'alternativas' => ['import numpy as np from scipy import stats np.mean(age) stats.mode(age)', 'import pandas as pd from scipy import stats pd.mean(age) stats.mode(age)', 'import numpy as np import pandas as pd np.mean(age) pd.mode(age)', 'from collections import Counter import numpy as np np.mean(age) Counter(age).most_common(1)', 'import pandas as pd from collections import Counter pd.mean(age) Counter(age).most_common(1)']],
            52 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Uma equipe de desenvolvimento precisa criar um sistema de gerenciamento de tarefas em que cada tarefa pode ter várias subtarefas e cada subtarefa pode ter várias subtarefas, e assim por diante. Para modelar essa estrutura de dados, qual das alternativas a seguir seria a mais adequada?', 'alternativas' => ['Array bidimensional', 'Lista encadeada', 'Árvore', 'Grafo', 'Tabela hash']],
            53 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Um engenheiro de software precisa criar um sistema que gerencie as relações entre clientes e produtos. Cada cliente pode comprar vários produtos, e cada produto pode ser comprado por vários clientes. Qual das alternativas a seguir é a melhor forma de modelar essa relação em um banco de dados relacional?', 'alternativas' => ['Usar uma tabela de clientes e uma tabela de produtos, com uma chave estrangeira de cliente na tabela de produtos.', 'Usar uma tabela de clientes e uma tabela de produtos, com uma chave estrangeira de produto na tabela de clientes.', 'Usar uma tabela de clientes, uma tabela de produtos e uma tabela intermediária que armazena a relação entre eles.', 'Usar uma única tabela com todos os dados de clientes e produtos.', 'Usar um banco de dados NoSQL, pois a relação é complexa.']],
            54 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'No contexto de segurança da informação, um programador precisa garantir que a senha do usuário seja armazenada de forma segura no banco de dados. Qual das alternativas a seguir é a melhor forma de fazer isso?', 'alternativas' => ['Armazenar a senha em texto plano.', 'Armazenar a senha criptografada com um algoritmo simétrico.', 'Armazenar a senha com hash, mas sem salt.', 'Armazenar a senha com hash e salt.', 'Armazenar a senha em um arquivo de texto separado.']],
            55 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Um programador precisa criar uma função em Python para calcular o n-ésimo número da sequência de Fibonacci de forma recursiva. Qual das alternativas a seguir implementa essa função de forma correta?', 'alternativas' => ['def fib(n): if n <= 1: return n else: return fib(n-1) + fib(n-2)', 'def fib(n): if n <= 1: return n else: return fib(n-1) * fib(n-2)', 'def fib(n): if n <= 1: return n else: return fib(n-1) - fib(n-2)', 'def fib(n): if n <= 1: return n else: return fib(n-1) / fib(n-2)', 'def fib(n): if n <= 1: return n else: return fib(n-1) % fib(n-2)']],
            56 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Qual o valor da variável `x` ao final da execução do seguinte código JavaScript? let x = 5; if (x > 3) { x += 2; } else { x -= 1; }', 'alternativas' => ['3', '7', '5', '6', '8']],
            57 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'No contexto de desenvolvimento web, um programador precisa criar uma página que se adapte a diferentes tamanhos de tela (computadores, tablets, smartphones). Qual das tecnologias a seguir é a mais indicada para essa finalidade?', 'alternativas' => ['Bootstrap', 'jQuery', 'CSS Flexbox e Grid', 'React', 'Angular']],
            58 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Um programador precisa criar um algoritmo para ordenar um array de números inteiros de forma crescente. Qual das alternativas a seguir é a melhor para essa finalidade?', 'alternativas' => ['Bubble Sort', 'Selection Sort', 'Insertion Sort', 'Merge Sort', 'Quick Sort']],
            59 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'No contexto de programação orientada a objetos (POO), o termo que se refere à capacidade de um objeto de se comportar de diferentes maneiras, dependendo de sua classe, é', 'alternativas' => ['Polimorfismo', 'Herança', 'Encapsulamento', 'Abstração', 'Interface']],
            60 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Um programador precisa criar um sistema de login em que a senha do usuário deve ser validada no lado do servidor. Qual das alternativas a seguir é a melhor forma de fazer isso?', 'alternativas' => ['Usar JavaScript para validar a senha no lado do cliente.', 'Usar HTML para validar a senha no lado do cliente.', 'Usar PHP para validar a senha no lado do servidor.', 'Usar CSS para validar a senha no lado do cliente.', 'Usar SQL para validar a senha no lado do servidor.']],
            61 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Um programador precisa criar um sistema de votação em que cada usuário pode votar apenas uma vez. Qual das alternativas a seguir é a melhor forma de garantir isso?', 'alternativas' => ['Usar um cookie para armazenar o voto do usuário.', 'Usar uma sessão para armazenar o voto do usuário.', 'Usar o IP do usuário para armazenar o voto.', 'Usar o e-mail do usuário para armazenar o voto.', 'Usar o ID do usuário para armazenar o voto.']],
            62 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Qual o valor da variável `y` ao final da execução do seguinte código JavaScript? let x = 10; let y = x > 5 ? x + 2 : x - 1;', 'alternativas' => ['12', '11', '9', '8', '10']],
            63 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Um programador precisa criar um algoritmo para encontrar o maior número em um array de números inteiros. Qual das alternativas a seguir é a melhor forma de fazer isso?', 'alternativas' => ['Usar um loop `for` e uma variável para armazenar o maior número.', 'Usar a função `Math.max()` do JavaScript.', 'Usar a função `sort()` do JavaScript e pegar o último elemento.', 'Usar a função `reduce()` do JavaScript.', 'Usar a função `map()` do JavaScript.']],
            64 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Qual o valor da variável `result` ao final da execução do seguinte código JavaScript? let x = "5"; let y = 2; let result = x + y;', 'alternativas' => ['7', '52', 'Error', 'NaN', 'undefined']],
            65 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Um programador precisa criar um formulário HTML em que o campo de senha deve ter no mínimo 8 caracteres. Qual das alternativas a seguir é a melhor forma de fazer isso?', 'alternativas' => ['Usar a propriedade `minlength` no campo de senha.', 'Usar a propriedade `maxlength` no campo de senha.', 'Usar a propriedade `pattern` no campo de senha.', 'Usar a propriedade `required` no campo de senha.', 'Usar a propriedade `type` no campo de senha.']],
            66 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'No contexto de desenvolvimento web, um programador precisa criar uma página que interaja com um banco de dados. Qual das tecnologias a seguir é a mais indicada para essa finalidade?', 'alternativas' => ['HTML', 'CSS', 'JavaScript', 'PHP', 'SQL']],
            67 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Um programador precisa criar um algoritmo para encontrar o menor número em um array de números inteiros. Qual das alternativas a seguir é a melhor forma de fazer isso?', 'alternativas' => ['Usar a função `Math.min()` do JavaScript.', 'Usar um loop `for` e uma variável para armazenar o menor número.', 'Usar a função `sort()` do JavaScript e pegar o primeiro elemento.', 'Usar a função `reduce()` do JavaScript.', 'Usar a função `map()` do JavaScript.']],
            68 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Qual o valor da variável `x` ao final da execução do seguinte código JavaScript? let x = 10; x += 5; x -= 2; x *= 3;', 'alternativas' => ['39', '15', '13', '45', '48']],
            69 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Um programador precisa criar uma função em Python para encontrar o índice de um elemento em um array. Qual das alternativas a seguir é a melhor forma de fazer isso?', 'alternativas' => ['Usar o método `index()` do array.', 'Usar o método `find()` do array.', 'Usar o método `search()` do array.', 'Usar o método `indexOf()` do array.', 'Usar o método `findIndex()` do array.']],
            70 => ['disciplina_id' => $disciplinas['Tecnologia da Informação'], 'enunciado' => 'Uma das formas de o gerente de uma agência bancária acompanhar a qualidade dos serviços prestados aos seus clientes é verificar o estado da ordem de atendimento em vários instantes ao longo do expediente. O sistema que a gerência utiliza para tal fim é a estrutura de dados conhecida como FILA, que mostra a situação da ordem de atendimento no instante da verificação. Nesse contexto, implementa-se uma estrutura de FILA de números inteiros com suas duas operações tradicionais: ENFILEIRAR(Z), que ocorre no instante em que um cliente recebe uma senha Z e entra na FILA; e DESENFILEIRAR( ), que ocorre quando um cliente sai da FILA, caso em que DESENFILEIRAR( ) retorna o número da senha. Sabe-se, também, que a representação do estado da FILA em um instante qualquer é realizada listando os elementos, de forma que o primeiro elemento, da esquerda para a direita, é o mais antigo presente na FILA. Nas condições apresentadas, considere uma FILA que começa vazia e realiza as seguintes operações: ENFILEIRAR(8) → ENFILEIRAR(9) → DESENFILEIRAR( ) → ENFILEIRAR(10) → ENFILEIRAR(11) → ENFILEIRAR(DESENFILEIRAR ( )) → ENFILEIR...', 'alternativas' => ['...']],
        ];

        foreach ($questoesData as $numeroQuestao => $data) {
            $questaoId = DB::table('questoes')->insertGetId([
                'prova_id' => $provaId,
                'disciplina_id' => $data['disciplina_id'],
                'enunciado' => $data['enunciado'],
                'gabarito_id' => null, // Será atualizado depois
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            $alternativasIds = [];
            foreach ($data['alternativas'] as $key => $alternativaTexto) {
                $alternativaId = DB::table('alternativas')->insertGetId([
                    'questao_id' => $questaoId,
                    'texto' => $alternativaTexto,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
                $alternativasIds[chr(65 + $key)] = $alternativaId;
            }

            // Atualiza a questão com o gabarito
            $gabaritoCorreto = $gabarito[$numeroQuestao] ?? null;
            if ($gabaritoCorreto && $gabaritoCorreto !== 'Anulada') {
                if (isset($alternativasIds[$gabaritoCorreto])) {
                    DB::table('questoes')
                        ->where('id', $questaoId)
                        ->update(['gabarito_id' => $alternativasIds[$gabaritoCorreto]]);
                } else {
                    // Loga/avisa para ajuste de dados (sem quebrar o seed)
                    echo "[AVISO] Questão {$numeroQuestao}: gabarito '{$gabaritoCorreto}' não existe entre as alternativas disponíveis ("
                        . implode(',', array_keys($alternativasIds)) . ").\n";
                }
            }
        }
    }
}
